[versions]
# libraries
annotations = "24.0.1"

# plugins
kotlin = "1.8.22"
changelog = "2.1.0"
gradleIntelliJPlugin = "1.15.0"
qodana = "0.1.13"
lombok = "8.0.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }